### ISSUE TITLE
Error while docker run deepstack-ui

### ISSUE THREAD

**Issue by OmegaMonster** [robmarkcole/deepstack-ui#74]
Hello @robmarkcole, I have encountered such issue while docker run the deepstack-ui. I have stated the final two lines for your reference.

```
raise OSError(err, os.strerror(err))
OSError: [Errno 38] Function not implemented
```

**Comment by robmarkcole** [comment]
Can you include the rest of the output?

**Comment by OmegaMonster** [comment]
Hi @robmarkcole

First and foremost I'll explain my setup. Im running home assistant on raspberry pi 3b+ whereas the macbook air m1 as deepstack server. So, I have docker up the deepstack,deepstack trainer at the macbook whereas do configuration at my raspberry pi side. Moreover, I have added the deepstack_face at my home assistant too. I've exactly followed as shown in the video : https://youtu.be/XPs0J1EQhK0 

But it seems like no response at home assistant whenever the image processing scan. I just encountered the deepstack-ui and curious does this able to help my situation. I have attached the error obtained for the deepstack-ui

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Traceback (most recent call last):
  File "/usr/local/bin/streamlit", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/streamlit/cli.py", line 233, in main_run
    _main_run(target, args)
  File "/usr/local/lib/python3.8/site-packages/streamlit/cli.py", line 261, in _main_run
    bootstrap.run(file, command_line, args)
  File "/usr/local/lib/python3.8/site-packages/streamlit/bootstrap.py", line 287, in run
    server.add_preheated_report_session()
  File "/usr/local/lib/python3.8/site-packages/streamlit/server/server.py", line 543, in add_preheated_report_session
    session = self._create_or_reuse_report_session(ws=None)
  File "/usr/local/lib/python3.8/site-packages/streamlit/server/server.py", line 577, in _create_or_reuse_report_session
    session = ReportSession(
  File "/usr/local/lib/python3.8/site-packages/streamlit/report_session.py", line 95, in __init__
    self._local_sources_watcher = LocalSourcesWatcher(
  File "/usr/local/lib/python3.8/site-packages/streamlit/watcher/local_sources_watcher.py", line 90, in __init__
    self._register_watcher(
  File "/usr/local/lib/python3.8/site-packages/streamlit/watcher/local_sources_watcher.py", line 130, in _register_watcher
    watcher=FileWatcher(filepath, self.on_file_changed),
  File "/usr/local/lib/python3.8/site-packages/streamlit/watcher/event_based_file_watcher.py", line 79, in __init__
    file_watcher.watch_file(file_path, on_file_changed)
  File "/usr/local/lib/python3.8/site-packages/streamlit/watcher/event_based_file_watcher.py", line 149, in watch_file
    folder_handler.watch = self._observer.schedule(
  File "/usr/local/lib/python3.8/site-packages/watchdog/observers/api.py", line 297, in schedule
    emitter.start()
  File "/usr/local/lib/python3.8/site-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/usr/local/lib/python3.8/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/usr/local/lib/python3.8/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/local/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 155, in __init__
    Inotify._raise_error()
  File "/usr/local/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 405, in _raise_error
    raise OSError(err, os.strerror(err))
OSError: [Errno 38] Function not implemented`

**Comment by robmarkcole** [comment]
Mac m1 might be the issue: see `The requested image's platform (linux/amd64) does not match the detected host platform` you may need some additional command when running deepstack. Preferentially run on an intel machine. What command have you used to run the ui?

**Comment by robmarkcole** [comment]
OK I also have an M1 and can reproduce that error - it means deepstack is not running or not reachable. Please debug and use the deepstack forums. Thanks
